import type { Metadata } from "next";
import { fontSans } from "./font";
import "./globals.css";
import { cn                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          } from "@/utils/cn";
import { ThemeProvider } from "@/components/ThemeProvider";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { ModeToggle } from "@/components/ui/ThemeToggle";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="dark">
            <body
                className={cn(
                    "min-h-screen bg-background font-sans antialiased bg-grid-slate-100 dark:bg-grid-white/[0.02]",
                    fontSans.variable
                )}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <div className="relative w-full flex items-center justify-center">
                        {/* <Navbar /> */}
                    </div>
                    {children}
                    <ModeToggle />
                    <Footer />
                </ThemeProvider>
            </body>
        </html>
    );
}
